version: '3.8'
services:
  app_python:
    image: kirillfedoseev/app_python:latest
    ports:
      - 80:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: syslog
      options: {tag: '{{.Name}}/{{.ID}}'}
