- name: Install docker and pip
  hosts: docker
  become: true
  vars:
    docker_install_compose: true
    docker_users:
      - ubuntu
    pip_install_packages:
      - name: docker
      - name: docker-compose
  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.pip
- name: Install app
  hosts: docker
  remote_user: ubuntu
  roles:
    - role: '../roles/app_python'